include:
- ./functions/health.py
kind: ArchiveUploadSpec
name: functions-health-py-nnTl

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: health-c3360e9c-91e1-4e0a-beb9-8de3f2c558f1
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://functions-health-py-nnTl
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2025-05-16T11:27:05Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: health
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: health-c3360e9c-91e1-4e0a-beb9-8de3f2c558f1
      namespace: ""
  requestsPerPod: 1
  resources: {}
  secrets:
  - name: elastic-secret
    namespace: ""
