apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: transobservations
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python39
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: transobservations.main
    packageref:
      name: transobservations-pkg
      namespace: ""
  requestsPerPod: 1
  resources: {}
  secrets:
  - name: elastic-secret
    namespace: ""
