apiVersion: fission.io/v1
kind: MessageQueueTrigger
metadata:
  creationTimestamp: null
  name: trans-harvester-mqtrigger
spec:
  contentType: application/json
  cooldownPeriod: 300
  errorTopic: errors
  functionref:
    functionweights: null
    name: transharvester-reddit
    type: name
  maxReplicaCount: 100
  maxRetries: 3
  messageQueueType: redis
  metadata:
    address: redis-headless.redis.svc.cluster.local:6379
    listLength: "100"
    listName: trans:subreddit
  minReplicaCount: 0
  mqtkind: keda
  pollingInterval: 30
  respTopic: observations
  topic: trans:subreddit
