include:
- ./function/transHarvester/transHarvester.py
- ./function/transHarvester/requirements.txt
kind: ArchiveUploadSpec
name: function-transharvester-transharvester-py-XBwW

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: transharvester-pkg
spec:
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://function-transharvester-transharvester-py-XBwW
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-15T21:23:07Z"
