include:
- ./functions/scoreHarvest/scoreHarvester.py
- ./functions/scoreHarvest/requirements.txt
kind: ArchiveUploadSpec
name: functions-scoreharvest-scoreharvester-py-OtZC

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: scoreharvester-pkg
spec:
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-scoreharvest-scoreharvester-py-OtZC
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-10T17:50:53Z"
