include:
- ./functions/enqueue/__init__.py
- ./functions/enqueue/enqueue.py
- ./functions/enqueue/requirements.txt
- ./functions/enqueue/build.sh
kind: ArchiveUploadSpec
name: functions-enqueue---init---py-ateA

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: enqueue-pkg
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-enqueue---init---py-ateA
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-17T11:17:55Z"
