include:
- ./functions/aflHarvester/aflHarvester.py
- ./functions/aflHarvester/requirements.txt
kind: ArchiveUploadSpec
name: functions-aflharvester-aflharvester-py-1glp

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: aflharvester-pkg
spec:
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-aflharvester-aflharvester-py-1glp
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-12T14:42:25Z"
