include:
- ./functions/checkelastic/__init__.py
- ./functions/checkelastic/checkelastic.py
- ./functions/checkelastic/requirements.txt
- ./functions/checkelastic/build.sh
kind: ArchiveUploadSpec
name: functions-checkelastic---init---py-E76z

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: checkelastic-pkg
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-checkelastic---init---py-E76z
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-16T13:53:33Z"
