include:
- ./function/transHarvester.py
- ./function/requirements.txt
- ./function/build.sh
kind: ArchiveUploadSpec
name: function-transharvester-py-YqKQ

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: transport-pkg
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://function-transharvester-py-YqKQ
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-14T07:53:14Z"
