include:
- ./functions/aHarvester/__init__.py
- ./functions/aHarvester/aHarvester.py
- ./functions/aHarvester/requirements.txt
- ./functions/aHarvester/build.sh
kind: ArchiveUploadSpec
name: functions-aharvester---init---py-7XwG

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: aharvester-pkg
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-aharvester---init---py-7XwG
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-17T11:17:05Z"
