apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: harvest-aflbluesky
spec:
  createingress: false
  functionref:
    functionweights: null
    name: harvest-aflbluesky
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /harvest_aflbluesky
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /harvest_aflbluesky
