apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: scoreharvester-route
spec:
  createingress: false
  functionref:
    functionweights: null
    name: scoreharvester
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /scoreharvester
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /scoreharvester
