apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: cleantext-route
spec:
  createingress: true
  functionref:
    functionweights: null
    name: textclean
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /text-clean
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /text-clean
