apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: transharvester-reddit-route
spec:
  createingress: true
  functionref:
    functionweights: null
    name: transharvester-reddit
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /transharvester
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /transharvester
