apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: blueskyfan-route
spec:
  createingress: true
  functionref:
    functionweights: null
    name: blueskyfan
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /blueskyfan
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /blueskyfan
