apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: fanpkg
spec:
  createingress: false
  functionref:
    functionweights: null
    name: fanpkg
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /fanpkg
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /fanpkg
