apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: addelastic-route
spec:
  createingress: true
  functionref:
    functionweights: null
    name: addelastic
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /addelastic
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /addelastic
