apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: afl-harvester-route
spec:
  createingress: true
  functionref:
    functionweights: null
    name: aflharvester
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /aflharvester
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /aflharvester
