apiVersion: fission.io/v1
kind: TimeTrigger
metadata:
  creationTimestamp: null
  name: aflsubred-timer
spec:
  cron: 0 */12 * * *
  functionref:
    functionweights: null
    name: aflsubred
    type: name
